---
title: "vizzes"
author: "Sam Loewen"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

## create weather data


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

##create a ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

```

alternate way

```{r}
weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
scatterplot = 
weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

scatterplot
```


```{r}
weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r}
weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) +   
geom_point(aes(color = name), alpha = .5)
```

```{r}
weather_df %>%
    ggplot(aes(x = tmin, y = tmax)) +   
geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
weather_df %>%
    ggplot(aes(x = date, y = tmax, color = name)) +   
geom_point(aes(size = prcp), alpha = .3) +
  geom_smooth(size = 2, se = FALSE)
```

```{r}

install.packages("hexbin")

weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d()
```

## more plots

```{r}
weather_df %>%
  ggplot(aes(x = tmax, color = name)) +
  geom_histogram()

weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram()

weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge", binwidth = 2)

weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(~name)

S
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)

ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

